Fix a lot of problems

diff --git a/bin/qsql-class b/bin/qsql-class
--- a/bin/qsql-class
+++ b/bin/qsql-class
@@ -8,7 +8,7 @@ else
     if [ `command -v java` ]; then
         JAVA_RUNNER="java"
     else
-        echo "JAVA_HOME is not set" >&2
+        echo "ERROR: JAVA_HOME is not set" >&2
         exit 1
     fi
 fi
@@ -19,7 +19,8 @@ if [[ "$JAVA_RUNNER" ]]; then
     read major minor extra <<<"$version";
     if (( major == 1 && minor < 8 ));
     then
-        echo "required java version > 1.8"
+        echo "ERROR: Required java version >= 1.8"
+        exit 1
     fi
 fi
 
@@ -29,7 +30,7 @@ else
     if [ `command -v spark-submit` ]; then
         SPARK_RUNNER="spark-submit"
     else
-        echo "SPARK_HOME is not set" >&2
+        echo "ERROR: SPARK_HOME is not set" >&2
         exit 1
     fi
 fi
@@ -39,13 +40,13 @@ if [[ "$SPARK_RUNNER" ]]; then
     IFS=.   read major minor extra <<< "$version";
     if (( major >= 2));
     then
-        if (( minor <= 2));
+        if (( minor < 2));
         then
-            echo "required spark version > 2.2"
+            echo "ERROR: Required spark version >= 2.2"
             exit 1
         fi
     else
-        echo "required spark version > 2.2"
+        echo "ERROR: Required spark version >= 2.2"
         exit 1
     fi
 fi
